spring:
  datasource:
    url: jdbc:sqlserver://ckp-mssql.database.windows.net:1433;database=ckp-mssql;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: ckpmssql
    password: Qwertyui@900
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


